config/routes.rb
Rails.application.routes.draw do
  root to: 'teams#index'

  resources :teams do
  	resources :comments
  end
  resources :players
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # validates_presence_of :title
  validates_presence_of :body
  validates_presence_of :username

  belongs_to :team
end

app/models/player.rb
class Player < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :position
  validates_presence_of :number
  validates_presence_of :birthday
  #validates_uniqueness_of :number
  belongs_to :team
end

app/models/team.rb
class Team < ActiveRecord::Base

  validates_presence_of :name
  validates_length_of :name, :minimum => 2
  validates_uniqueness_of :name

  has_many :players

  has_many :comments

  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  has_many :teams

  def team
    teams.first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def index
    @comments = Comment.all
  end
  def create
    @team = Team.find(params[:team_id])
    @comment = @team.comments.create(comment_params)
    redirect_to team_path(@team)


    /@comment = Comment.new comment_params
    
    if @comment.save
      redirect_to root_path
    else
      render :new
    end/
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to :action => 'show', :id => @comment
  end

  def destroy
    @comment=Comment.find(params[:id])
    @comment.destroy
    redirect_to :action => 'index'
  end

  private

  def comment_params
    params.require(:comment)
    .permit(:username,:title,:body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def new
    @player = Player.new
  end

  def index
    @players = Player.all
  end
  def create
    @player = Player.new player_params
    
    if @player.save
      
      redirect_to team_path(current_user.team.id)
    else
      render :new
    end
  end

  def show
    @player = Player.find(params[:id])
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])

    if @player.update(player_params)
      redirect_to :action => 'show', :id => @player
    else
      render :edit
    end
  end

  def destroy
    @player=Player.find(params[:id])
    @player.destroy
    redirect_to team_path(current_user.team.id)
  end

  private

  def player_params
    params.require(:player)
    .permit(:name,:position,:number,:birthday)
    .merge(team_id: current_user.team.id)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def new
    @team = Team.new
  end

  def index
    @teams = Team.all
  end
  def create

    @team = Team.new team_params

    #teamExist = Team.find_by_name('rui')
    if @team.save
      redirect_to root_path
    else
      render :new
    end      

  end

  def show
    @team = Team.find(params[:id])
  end

  def edit
    @team = Team.find(params[:id])
  end

  def update
    @team = Team.find(params[:id])
    
    if @team.update(team_params)
      redirect_to :action => 'show', :id => @team
    else
      render :edit
    end
  end

  def destroy
    @team=Team.find(params[:id])
    @team.destroy
    redirect_to :action => 'index'
  end

  private

  def team_params
    params.require(:team)
    .permit(:name)
    .merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/edit.html.erb
<h1>Edit an Comment</h1>

<%= form_for(@comment) do |f| %>
  <ul>
  <% @comment.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_field :body %>
  </p>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/index.html.erb
<% if @comment.blank? %>
<p>There are not any comment currently in the system.</p>
<% else %>
<div class="panel panel-default">
	<!-- Default panel contents -->
	<div class="panel-heading">
		<h2>Players</h2>
	</div>

	<!-- Table -->
	<table class="table">
	<thead>
		<tr>
			<th>Username</th>
			<th>Title</th>
			<th>Comment</th>
		</tr>
	</thead>
	<tbody>
		<% @comment.each do |c| %>
		<tr>
			<th>
				<%= link_to c.username, {:action => 'show', :id => c.id} -%>
			</th>
			<th>
				<%= link_to c.title, {:action => 'show', :id => c.id} -%>
			</th>
			<th>
				<%= link_to c.body, {:action => 'show', :id => c.id} -%>
			</th>
		</tr>
			<% end %>
		</tbody>
		</table>
	</div>

	<% end %>

app/views/comments/new.html.erb
<div class="row">
	<h1>Create Comment</h1>
</div>
<% if @comment.errors.full_messages!=[] %>
	<div class="row">
		<%= @comment.errors.full_messages %>
	</div>
<% end %>
<div class="body_view">

	<%= form_for @comment do |form| %>
		<div class="row">
			<%= form.label :username %>
			<%= form.text_field :username %>
			<%= form.label :title %>
			<%= form.text_field :title %>
			<%= form.label :body %>
			<%= form.text_field :body %>
			<%= form.submit class: 'button' %>
		</div>
	<% end %>
</div>

app/views/comments/show.html.erb
<h1><%= @comment.username %></h1>
<h3><%= @comment.title %></h3>
<h3><%= @comment.body %></h3>
<li>
<b> <%= link_to 'Back', {:action => 'index'}%></b>
<span>  |  </span>
<b> <%= link_to 'Edit', {:action => 'edit', :id => @comment.id} %></b>
<span>  |  </span>
<b> <%= link_to 'Destroy', comment_path(@comment), method: :delete, data: { confirm: 'Are you sure?' } %></b>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyFavoriteTeam</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="holder">
    <div id="body">
      <div class="top_banner">
        <div class="container">
          <div class="line_signin">
            <% if signed_in? %>
            <%= link_to 'Sign out', sign_out_path, method: :delete , :class => "btn_sign"%>
            <% else %>
            <%= link_to 'Sign in', sign_in_path, :class => "btn_sign"%>
            <% end %>
            <div class="name_sign">
              <% if signed_in? %>
              Hello <%= current_user.email %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="banner">
        <div class="container">
          <div class="menu">
            <% if signed_in? %>
            <% if current_user.team %>
            <%= link_to 'MyTeam', team_path(current_user.team) , :class => "btn_menu"%>
            <% else %>
            <%= link_to 'MyTeam', new_team_path , :class => "btn_menu"%>
            <% end %>
            <%else%>
            <%= link_to 'MyTeam', sign_in_path , :class => "btn_menu"%>
            <%end%>
            <a href="/teams/" class="btn_menu">Teams</a>
            <a href="/players/" class="btn_menu">Players</a>
          </div>
        </div>
      </div>
      <div class="views">
        <div class="container">
          <%= yield %>
        </div>
      </div>
    </div>
    <footer class="footer">
      <div class="container">Design by Grupo 5</div>
    </footer>
  </div> 
</body>
</html>

app/views/pages/home.html.erb
<% if signed_in? && current_user.team %>
  <h1><%= current_user.team.name %></h1>
  <% current_user.team.players.each do |player| %>
		<tr>
			<th>
				<%= link_to player.name, player_path(player) -%>
			</th>

		</tr>
	<% end %>
<% else %>
  <%= link_to 'Create Team', new_team_path %>
<% end %>

app/views/players/edit.html.erb
<div class="page-header">
  <h2>Edit <small>Player</small></h2>
</div>

  
<div class="form-horizontal">
  <div class="form-group">
    <div class="col-sm-10">
      <% if @player.errors.any? %>
        <div class="alert alert-danger col-md-10" role="alert">
            <span class="sr-only">Error:</span>
              <% @player.errors.full_messages.each do |message| %>
              <p>* <%= message%>  </p>
            <%end%>
        </div>    
      <% end %>
    </div>  
  </div>  

  

<p></p>

  <%= form_for @player do |form|  %>
    <div class="form-group">
      <%= form.label :name, class: 'control-label col-sm-2' %>
      <div class="col-sm-10">
        <%= form.text_field :name, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :position, class: 'control-label col-sm-2'%>
      <div class="col-sm-10">
        <%= form.text_field :position, class: 'form-control'%>
      </div>
    </div>  
    <div class="form-group">
      <%= form.label :number, class: 'control-label col-sm-2' %>
      <div class="col-sm-10">
        <%= form.text_field :number, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :birthday, class: 'control-label col-sm-2' %>
      <div class="col-sm-10">
        <%= form.text_field :birthday, class: 'form-control'%>
      </div>  
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= form.submit class: 'btn btn-default' %>
      </div>
    </div>    

  <% end %>

</div>

 <script>
  $('#player_birthday').datepicker(
    {
      changeMonth: true,
          changeYear: true

    });

  </script>

app/views/players/index.html.erb
<% if @players.blank? %>
<p>There are not any players currently in the system.</p>
<% else %>
	<div class="page-header">
		<h2>Players <small>List</small></h2>
	</div>

	<!-- Table -->
	<table class="table">
		<thead>
			<tr>
				<th>Name</th>
				<th>Position</th>
				<th>Number</th>
				<th>Birthday</th>
				<th>Team Number</th>
			</tr>
		</thead>
		<tbody>
			<% @players.each do |c| %>
			<tr>
				<th>
					<%= link_to c.name, {:action => 'show', :id => c.id} -%>
				</th>
				<th>
					<%= link_to c.position, {:action => 'show', :id => c.id} -%>
				</th>
				<th>
					<%= link_to c.number, {:action => 'show', :id => c.id} -%>
				</th>
				<th>
					<%= link_to c.birthday, {:action => 'show', :id => c.id} -%>
				</th>
				<th>
					<%= link_to c.team_id, team_path(c.team_id), method: :get -%>
				</th>
			</tr>
			<% end %>
		</tbody>
	</table>

<% end %>

app/views/players/new.html.erb
<div class="page-header">
  <h2>Create <small>Player</small></h2>
</div>

	
<div class="form-horizontal">
	<div class="form-group">
		<div class="col-sm-10">
			<% if @player.errors.any? %>
				<div class="alert alert-danger col-md-10" role="alert">
	  				<span class="sr-only">Error:</span>
	  					<% @player.errors.full_messages.each do |message| %>
							<p>* <%= message%>	</p>
						<%end%>
				</div>		
			<% end %>
		</div>	
	</div>	


	<%= form_for @player do |form|  %>
		<div class="form-group">
			<%= form.label :name, class: 'control-label col-sm-2' %>
			<div class="col-sm-10">
				<%= form.text_field :name, class: 'form-control' %>
			</div>
		</div>
		<div class="form-group">
			<%= form.label :position, class: 'control-label col-sm-2'%>
			<div class="col-sm-10">
				<%= form.text_field :position, class: 'form-control'%>
			</div>
		</div>	
		<div class="form-group">
			<%= form.label :number, class: 'control-label col-sm-2' %>
			<div class="col-sm-10">
				<%= form.text_field :number, class: 'form-control' %>
			</div>
		</div>
		<div class="form-group">
			<%= form.label :birthday, class: 'control-label col-sm-2' %>
			<div class="col-sm-10">
				<%= form.text_field :birthday, class: 'form-control'%>
			</div>	
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<%= form.submit class: 'btn btn-default' %>
			</div>
		</div>		

	<% end %>

</div>

 <script>
 	$('#player_birthday').datepicker(
 		{
 			changeMonth: true,
      		changeYear: true

 		});

  </script>

app/views/players/show.html.erb
<div class="page-header">
    <h2>Name: <small><%= @player.name %></small></h2>
</div>
<div class="page-header">
    <h2>Position: <small><%= @player.position %></small></h2>
</div>
<div class="page-header">
    <h2>Number: <small><%= @player.number %></small></h2>
</div>
<div class="page-header">
    <h2>Birthday: <small><%= @player.birthday %></small></h2>
</div>


<b> <%= link_to 'Back', {:action => 'index'}, class: "btn btn-default"%>
    <% if signed_in? && @player.team_id==current_user.team.id%>
    <b> <%= link_to 'Edit', {:action => 'edit', :id => @player.id}, class: "btn btn-default" %></b>

    <button class="btn btn-default" data-toggle="modal" data-target="#myModal"> Destroy</button>
    <% end -%>
    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Remove player <%=@player.name%></h4>
                </div>
                <div class="modal-body">
                    <div class="form-horizontal">                  
                        <h3 class="modal-title">Are you sure?</h3>   
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" ng-click="cancelar()" data-dismiss="modal">No</button>
                    <a class="btn btn-danger" rel="nofollow" data-method="delete" href="/players/<%=@player.id%>">Yes</a>
                </div>
            </div>
        </div>
    </div>